language: python
python:
  - "2.7"
dist: trusty
sudo: required

branches:
  only:
    - master

cache:
  - pip

install:
  - pip install flake8
  - pip install tox==2.6.0
  - pip install psycopg2

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"
  apt:
    packages:
      - nginx

script:
  - flake8 .
  - tox .
