
---
  # travis.yml for Django
  sudo: required
  dist: trusty

  language: python
  python:
    - 2.7

  branches:
    only:
      - master

  services:
    - postgresql
    - redis-server

  addons:
    postgresql: "9.6"

  before_install:
    - export DJANGO_SETTINGS_MODULE=atmosphere.settings
    - sudo pg_dropcluster --stop 9.2 main
    - sudo pg_dropcluster --stop 9.3 main
    - sudo pg_dropcluster --stop 9.4 main
    - sudo pg_dropcluster --stop 9.5 main
    - sudo pg_lsclusters # For testing purposes

  install:
    - pip install flake8
    - pip install tox==2.6.0
    - pip install -r requirements.txt -r dev_requirements.txt

  before_script:
    - psql -c "CREATE USER atmosphere_db_user WITH PASSWORD 'atmosphere_db_pass' CREATEDB;" -U postgres
    - psql -c "CREATE DATABASE atmosphere WITH OWNER atmosphere_db_user;" -U postgres

  script:
    - flake8
    - cp ./variables.ini.dist ./variables.ini
    - ./configure
    - tox


