# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20170224_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmosphereuser',
            name='os_domain_name',
        ),
        migrations.RemoveField(
            model_name='atmosphereuser',
            name='os_user_id',
        ),
    ]
