# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20170410_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='os_domain_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='os_project_id',
        ),
    ]
