# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=256)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Identity')),
            ],
            options={
                'db_table': 'sahara_job',
            },
        ),
    ]
